### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging' with latest docker image

### ISSUE THREAD

**Issue by aniketpawar1305** [ansible/awx-ee#131]
Hello,

We are using latest docker image for our AWX-EE deployment.  But, facing one issue while running our playbooks which we have developed based on azure modules.
Here we are using azure modules like: azure_rm_manageddisk, azure_rm_networkinterface etc.
While running the ansible playbooks AWX-EE is throwing "ModuleNotFoundError" error for 'packaging'. On the other hand playbooks are working as expected with Ansible.
Please find the below error screenshot:
![image](https://user-images.githubusercontent.com/72486852/185617184-5a00b90b-68e0-489b-8c66-04369a0ad4e4.png)
  
AWX Environment Details:

ansible-playbook [core 2.12.5.post0]
config file = None
configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/local/bin/ansible-playbook
python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
jinja version = 2.11.3
libyaml = True

Sample Playbooks:

![image](https://user-images.githubusercontent.com/72486852/185915831-90420a90-f47c-48db-a780-a1c8e2b62301.png)

![image](https://user-images.githubusercontent.com/72486852/185916027-6cca85c1-74b1-4da0-8966-a064e3c41afc.png)

Please do let me know if you need any further details.

**Comment by fosterseth** [comment]
Hello @aniketpawar1305! The awx-ee contains the collections and dependencies needed for supported AWX features to function. Anything beyond that (like your 'packaging' module) will require you to build your own EE. For information on how to do that, see https://ansible-builder.readthedocs.io/en/stable/

let us know if that helps

**Comment by akus062381** [comment]
Hi @aniketpawar1305!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
