### ISSUE TITLE
docker image error tag latest

### ISSUE THREAD

**Issue by linuxem** [ansible/awx-ee#145]
On the latest image, I am getting the error  "exec /bin/sh: input/output error" when trying deploy on the Kubernetes cluster
I fixed it by using the image tag as follows:  
awx-ee@sha256:2cb145011f6f7340e41e3b3d787b53873b795ccede72d5b5ea8c0eeeb88d55fe

![awx-ee](https://user-images.githubusercontent.com/936059/197061644-7182cd17-30ba-472a-a310-f21eceab0aa7.jpeg)

**Comment by fosterseth** [comment]
@linuxem  does `awx-ee:latest` pull fine now?

**Comment by djyasin** [comment]
Hi!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
