### ISSUE TITLE
AWX-EE with python 3.10

### ISSUE THREAD

**Issue by thxcodes** [ansible/awx-ee#152]
do you know how to create a awx-ee custom environment with python 3.10 installed? i'm make it but ansible-builder install python 3.8

**Comment by fosterseth** [comment]
@thxcodes in ansible-builder, you can use the `_build/bindep.txt` to specify a python version, see an example in awx-ee here

https://github.com/fosterseth/awx-ee/blob/devel/_build/bindep.txt#L1

let us know if that helps

**Comment by thxcodes** [comment]
@fosterseth 
i did it 

python310-devel [platform:rpm compile]

but not works

**Comment by fosterseth** [comment]
@thxcodes awx-ee is based on the ansible-runner image, which is based on centos 8, which doesn't support python310-devel officially https://pkgs.org/download/python310-devel

you may need to create your own EE_BASE_IMAGE by pulling down ansible-runner and enabling that repo and creating a new image and push the image to a public image repository (like quay). Then your execution-environment.yml `EE_BASE_IMAGE` can point to that new image with the repo enabled so that it can successfully install python310-devel

**Comment by relrod** [comment]
We've just upgraded the EE to be based on CentOS Stream 9. This has Python 3.9 (not 3.10) but I wonder if that might be new enough for you? Otherwise, I would suggest (as above) making your own EE.

Potentially you could use the official EE as a base image and just modify it some. You could compile Python 3.10 from an upstream .tar.gz in your image, or try to find an RPM with it and install that.

In any case, this is more of a support question, so if you need more help, I'd suggest sending a message to the mailing list or joining our Matrix chat and we'll be glad to help more, as able! With that in mind, I'm going to close this out and get it out of our queue :)
