### ISSUE TITLE
[constructed-inventory][dev-only] build temporary awx-ee for ansible/ansible#79596

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/awx-ee#158]
for ansible/ansible#79596

**Comment by relrod** [comment]
Refs https://github.com/ansible/awx-ee/pull/160

This is work that Shane did and I re-did before I realized he did it. I came up with an almost identical solution, which makes me think this is about the best we will do for now.

I went with his work in the PR (as opposed to my implementation) because it was ever-so-slightly more elegant than mine, though the end result looked basically identical.

If/when this lands, we can easily modify it to make an image that includes that ansible/ansible patch.

**Comment by TheRealHaoLiu** [comment]
[quay.io/relrod/awx-ee-invlimit:latest](http://quay.io/relrod/awx-ee-invlimit:latest)
