### ISSUE TITLE
Need support for Terraform state inventory

### ISSUE THREAD

**Issue by akira6592** [ansible/awx-ee#240]
AWX [24.0.0](https://github.com/ansible/awx/releases/tag/24.0.0) introduced terraform state inventory source.

However, the current awx-ee does not have `cloud.terraform` collection and terraform binary.

In  "[AWX Terraform State Inventory Source](https://www.youtube.com/watch?v=V7sNHspRriI)" demo uses `execution-environment.yml` in @hakbailey repository https://github.com/hakbailey/terraform-aap-demo .

**Comment by tima** [comment]
@akira6592 AWX is a stream of development work so in this case some features got merged and released before others including (I think) all of the docs.

That said, HashiCorp's BSL license forbids 3rd party distribution of the terraform binary or code so we cannot include it in any EE that the project distributes. The `cloud.terraform` collection could be included, but is pretty worthless until the terraform binary gets baked in.

This issue should be marked "wont fix" because we can't do much more than document how users can build their own EE for this functionality to work.

**Comment by akira6592** [comment]
@tima Thank you. I understand.

**Comment by akira6592** [comment]
I found the useful repository.

https://github.com/ansible-cloud/terraform_ee

> Example for building an Ansible execution environment with TerraForm dependencies built in.
