### ISSUE TITLE
bash: /opt/builder/bin/entrypoint: Permission denied

### ISSUE THREAD

**Issue by aoforb** [ansible/awx-ee#256]
Anyone know why I'm getting `bash: /opt/builder/bin/entrypoint: Permission denied
`

I've made no changes to the code.

Cheers

**Comment by aoforb** [comment]
Adding `- RUN chmod 777 /opt/builder/bin/entrypoint` to `append_final` fixes the problem.

**Comment by mateuszdrab** [comment]
The same happened to me, so perhaps this issue should be left opened

**Comment by patbec** [comment]
Hi,
I had the same problem and was able to find the cause.

Everything worked on my MacBook after a build, but not on the customer's system.

If `fuse-overlay` is used as the Podman storage driver instead of the kernel `overlay`, different SELinux labels are set:

```shell
# Build
ansible-builder build --file './company-supported-rhel9/execution-environment.yml' --context './context-company-supported-rhel9' --verbosity='3'

# Run and override the default entrypoint `/opt/builder/bin/entrypoint` for testing
podman run --entrypoint /bin/bash -it --rm company-supported-rhel9-mac
bash-5.1$ ls -lZ /opt/builder/bin/entrypoint
-rwxr-xr-x. 1 root root system_u:object_r:container_file_t:s0:c186,c261 5909 Aug 20 15:03 /opt/builder/bin/entrypoint
bash-5.1$ findmnt -T /opt/builder/bin/entrypoint
TARGET SOURCE  FSTYPE  OPTIONS
/      overlay overlay rw,relatime,context=“system_u:object_r:container_file_t:s0:c186,c261”,lowerdir=/var/home/core/.local/share/con...
bash-5.1$ id -u
1000
bash-5.1$ id -g
0

# Run the container with the permission denied exception
podman run --entrypoint /bin/bash -it --rm company-supported-rhel9-customer
bash-5.1$ ls -lZ /opt/builder/bin/entrypoint
-rwxr-xr-x. 1 root root system_u:object_r:fusefs_t:s0:c186,c261 5909 Aug 20 15:03 /opt/builder/bin/entrypoint
bash-5.1$ findmnt -T /opt/builder/bin/entrypoint
TARGET SOURCE  FSTYPE  OPTIONS
/      fuse-overlayfs fuse.fuse-overlayfs rw,nodev,noatime,user_id=0...
bash-5.1$ id -u
1000
bash-5.1$ id -g
0
```

If the configuration in `/etc/containers/storage.conf` is changed, a `podman system reset` must be run afterward. The `storage.conf` setting for the storage driver is cached in `~/.config/containers`.

A another possible cause could be the user:
Ansible-Builder uses `USER 1000` in its Containerfile, but there is no user listed in `/etc/passwd`. However, if you want to create a real user for a specific case, keep in mind that podman/ansible-builder uses GID 0 for this users:

```
additional_build_steps:
    append_base:
		RUN useradd runner --no-create-home \
                           --home-dir /runner \
                           --shell /bin/bash \
                           --uid 1000 \
                           --gid 0
```

Without the GID attribute, `1000` is also used for the primary group, which makes a difference.

I hope this helps someone.
